-- begin ORDERMANAGER_PRODUCT
alter table ORDERMANAGER_PRODUCT add constraint FK_ORDERMANAGER_PRODUCT_ON_SUPPLIER foreign key (SUPPLIER_ID) references ORDERMANAGER_SUPPLIER(ID)^
create index IDX_ORDERMANAGER_PRODUCT_ON_SUPPLIER on ORDERMANAGER_PRODUCT (SUPPLIER_ID)^
-- end ORDERMANAGER_PRODUCT
-- begin ORDERMANAGER_COUPON
alter table ORDERMANAGER_COUPON add constraint FK_ORDERMANAGER_COUPON_ON_PRODUCT foreign key (PRODUCT_ID) references ORDERMANAGER_PRODUCT(ID)^
create index IDX_ORDERMANAGER_COUPON_ON_PRODUCT on ORDERMANAGER_COUPON (PRODUCT_ID)^
-- end ORDERMANAGER_COUPON
-- begin ORDERMANAGER_TRANSACTION
alter table ORDERMANAGER_TRANSACTION add constraint FK_ORDERMANAGER_TRANSACTION_ON_ORDER foreign key (ORDER_ID) references ORDERMANAGER_ORDER(ID)^
create index IDX_ORDERMANAGER_TRANSACTION_ON_ORDER on ORDERMANAGER_TRANSACTION (ORDER_ID)^
-- end ORDERMANAGER_TRANSACTION
-- begin ORDERMANAGER_ORDER_ITEM
alter table ORDERMANAGER_ORDER_ITEM add constraint FK_ORDERMANAGER_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references ORDERMANAGER_ORDER(ID)^
alter table ORDERMANAGER_ORDER_ITEM add constraint FK_ORDERMANAGER_ORDER_ITEM_ON_SUPPLIER foreign key (SUPPLIER_ID) references ORDERMANAGER_SUPPLIER(ID)^
create index IDX_ORDERMANAGER_ORDER_ITEM_ON_ORDER on ORDERMANAGER_ORDER_ITEM (ORDER_ID)^
create index IDX_ORDERMANAGER_ORDER_ITEM_ON_SUPPLIER on ORDERMANAGER_ORDER_ITEM (SUPPLIER_ID)^
-- end ORDERMANAGER_ORDER_ITEM
-- begin ORDERMANAGER_ORDER
alter table ORDERMANAGER_ORDER add constraint FK_ORDERMANAGER_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references ORDERMANAGER_CUSTOMER(ID)^
create index IDX_ORDERMANAGER_ORDER_ON_CUSTOMER on ORDERMANAGER_ORDER (CUSTOMER_ID)^
-- end ORDERMANAGER_ORDER
